language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env: 
    global:
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='scipy matplotlib pyyaml'
        
# commands to install dependencies (astropy, conda)
install: 
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

# command to run tests
script: 
    python setup.py test 